### ISSUE TITLE
Question: should `downgrade` be possible with only a `&mut PA0` mutable borrow?

### ISSUE THREAD

**Issue by luojia65** [japaric/stm32f30x-hal#34]
When I try to build my own HAL today, I read this `stm32f30x-hal` project and found code piece like this:
https://github.com/japaric/stm32f30x-hal/blob/3433e5463478c0dab8a2afea5e27cf815af89720/src/gpio.rs#L443-L454
According to code, this `downgrade` method on GPIO pins consumes the ownership of itself and produce an ownership of `PAx` partially erased pin which is more abstract, but I cannot restore the detailed `PA0` if it is downgraded into `PAx`:
```rust
let pa0 = dp.GPIOA.split(&mut ahb).pa0;
let pa0 = pa0.into_push_pull_output(&mut moder, &mut otyper);
{
    let pax = pa0.downgrade(); 
    // do something with pax
    pax.set_high().unwrap();
}
// wait, I cannot restore my pa0!
// let pa0 = pa0.into_floating_input(&mut moder, &mut otyper); // fails to compile
```
As [all of the methods](https://docs.rs/stm32f30x-hal/0.2.0/stm32f30x_hal/gpio/gpioa/struct.PAx.html) in `PAx` (if I am correct) requires a mutable borrow rather than consume the ownership of itself, we can downgrade this pin with a mutable borrow of itself like:
```rust
pub fn downgrade(&mut self) -> $PXx<Output<MODE>>
```
which we still hold the ownership of `PA0` and call some functions after `PAx` is dropped.
The Rust's `std` library uses `downgrade` function name with a borrow of itself.
https://doc.rust-lang.org/stable/std/rc/struct.Rc.html#method.downgrade
Is my thought reasonable? Should I write like the second piece of code for my new HAL project?

**Comment by chrysn** [comment]
A downgrade from &mut PA1 to PAx would run into lifetime issues -- as the PAx is owned, there wouldn't be any information on when the `PA1` is used again.

You might want to have a `downgrade_mutref(&'a mut PA1) -> &'a mut PAx` in parallel to the existing downgrade, but as there's no way on the stack to store the `i`. You could then return a `MutRefPAx<'a>` that can produce a `&'b mut PAx` for shorter lifetimes, but at that point things have gotten complex to the point where there has to be a very convincing use case.
